<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>services score</name>
  <uuid>61d228b7-9f28-459a-8ae1-9357b998c295</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the number of elements in the Services requested of Services  is more than 3
then
	add 1 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
