<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>set client input</name>
  <uuid>5f67e3eb-8c62-4dcb-8472-187a623ee4aa</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the clientannualrevenue is the Annual Revenue of 'Client information' ,
		the clientemployeenumber is the Number of Employees of 'Client information' ,
		the clientexistenceduration is the Company Age of 'Client information' ,
		the clientindustry is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
